site_name: Lepsta Docs

# Page tree
nav:
  - Home:
    - index.md
    - How Lepsta works: pages/lepsta/how-lepsta-works.md
  - Getting started:
    - Setup: pages/setup.md
    - Your first repository: pages/quick-start/your-first-repository.md
    - How streams work: pages/quick-start/how-streams-works.md
  - Guides:
    - Create a branch: pages/guides/create-a-branch.md
    - Create and Mount a repo: pages/guides/create-and-mount-repo.md
    - Create a workspace: pages/guides/create-a-workspace.md
    - Manage Repositories: pages/guides/manage-repositories.md
    - Manage Streams: pages/guides/manage-streams.md
  - Uju:
    - What is Uju?: pages/uju/what-is-uju.md
    - CLI: 
      - uju: pages/uju/cli/uju.md
      - uju apply: pages/uju/cli/uju_apply.md
      - uju cat: pages/uju/cli/uju_cat.md
      - uju changes: pages/uju/cli/uju_changes.md
      - uju commit: pages/uju/cli/uju_commit.md
      - uju config: pages/uju/cli/uju_config.md
      - uju diff: pages/uju/cli/uju_diff.md
      - uju discard: pages/uju/cli/uju_discard.md
      - uju download: pages/uju/cli/uju_download.md
      - uju export: pages/uju/cli/uju_export.md
      - uju init: pages/uju/cli/uju_init.md
      - uju log: pages/uju/cli/uju_log.md
      - uju login: pages/uju/cli/uju_login.md
      - uju logout: pages/uju/cli/uju_logout.md
      - uju ls: pages/uju/cli/uju_ls.md
      - uju merge: pages/uju/cli/uju_merge.md
      - uju repo: pages/uju/cli/uju_repo.md
      - uju repos: pages/uju/cli/uju_repos.md
      - uju rm: pages/uju/cli/uju_rm.md
      - uju state: pages/uju/cli/uju_state.md
      - uju states: pages/uju/cli/uju_states.md
      - uju stats: pages/uju/cli/uju_stats.md
      - uju switch: pages/uju/cli/uju_switch.md
      - uju system: pages/uju/cli/uju_system.md
      - uju token: pages/uju/cli/uju_token.md
      - uju update: pages/uju/cli/uju_update.md
      - uju validate: pages/uju/cli/uju_validate.md
  - Known issues:
      - This repo is in an inconsistent state: pages/issues/error-this-repo-is-in-an-inconsistent-state.md
      - Changes not showing on the platform: pages/issues/error-changes-not-showing-on-the-platform.md
      - Too many open files: pages/issues/error-too-many-open-files.md
      - Windows Firewall: pages/issues/windwos-firewall.md
  - Changelog:
    - Changelog: pages/changelog

theme:
  name: material
  custom_dir: overrides
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: preference
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_lepsta
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/lepsta
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/lepsta
extra_css:
  - stylesheets/extra.css
google_analytics:
  - UA-49518961-4
  - auto
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2020 - 2025. Lepsta Inc. & Lepsta (Pty) Ltd.